# Generated by Django 4.2.16 on 2025-01-25 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_Score_Details_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('state', models.TextField(max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'complaint_score_details_history',
            },
        ),
        migrations.CreateModel(
            name='Complaint_Score_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('original_id', models.IntegerField(default=0)),
                ('state', models.TextField(max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'complaint_score_details',
            },
        ),
    ]
