# Generated by Django 4.2.16 on 2025-01-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_score_details',
            name='reason',
            field=models.TextField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint_score_details_history',
            name='reason',
            field=models.TextField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
