# Generated by Django 4.2.16 on 2025-01-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_complaint_score_details_history_user_original_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_score_details_history_user',
            name='original_id',
        ),
        migrations.AddField(
            model_name='complaint_score_details',
            name='sign',
            field=models.TextField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint_score_details_history_user',
            name='sign',
            field=models.TextField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
