# Generated by Django 4.2.16 on 2025-01-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_remove_complaint_score_details_history_user_original_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_score_details_history',
            name='state',
            field=models.TextField(default='non', max_length=3),
            preserve_default=False,
        ),
    ]
