# Generated by Django 4.2.16 on 2025-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score_topics',
            name='all_score',
            field=models.IntegerField(default=0),
        ),
    ]
