# Generated by Django 4.2.16 on 2025-01-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_score_topics_all_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score_topics',
            name='all_score',
        ),
    ]
