# Generated by Django 4.2.16 on 2025-01-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_remove_score_topics_all_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_topics',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
