# Generated by Django 4.2.16 on 2025-02-03 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking_scores',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ranking_scores',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
