# Generated by Django 4.2.16 on 2025-02-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_scores_histories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scores_Histories',
        ),
    ]
